### ISSUE TITLE
V3.0.0

### ISSUE THREAD

**Issue by linnikvv** [ffplayout/ffplayout-engine#90]
```
Mar 17 22:13:38 flux systemd[1]: ffplayout-engine.service: Service RestartSec=1s expired, scheduling restart.
Mar 17 22:13:38 flux systemd[1]: ffplayout-engine.service: Scheduled restart job, restart counter is at 4.
Mar 17 22:13:38 flux systemd[1]: Stopped python and ffmpeg based playout.
Mar 17 22:13:38 flux systemd[1]: Started python and ffmpeg based playout.
Mar 17 22:13:38 flux python[10672]: Traceback (most recent call last):
Mar 17 22:13:38 flux python[10672]:   File "/opt/ffplayout-engine/ffplayout.py", line 24, in <module>
Mar 17 22:13:38 flux python[10672]:     from ffplayout.utils import _playout, stdin_args, validate_ffmpeg_libs
Mar 17 22:13:38 flux python[10672]:   File "/opt/ffplayout-engine/ffplayout/utils.py", line 340, in <module>
Mar 17 22:13:38 flux python[10672]:     backupCount=_log.backup_count)
Mar 17 22:13:38 flux python[10672]:   File "/usr/lib/python3.7/logging/handlers.py", line 199, in __init__
Mar 17 22:13:38 flux python[10672]:     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
Mar 17 22:13:38 flux python[10672]:   File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
Mar 17 22:13:38 flux python[10672]:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
Mar 17 22:13:38 flux python[10672]:   File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
Mar 17 22:13:38 flux python[10672]:     StreamHandler.__init__(self, self._open())
Mar 17 22:13:38 flux python[10672]:   File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
Mar 17 22:13:38 flux python[10672]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
Mar 17 22:13:38 flux python[10672]: PermissionError: [Errno 13] Permission denied: '/var/log/ffplayout/decoder.log'
Mar 17 22:13:38 flux systemd[1]: ffplayout-engine.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 22:13:38 flux systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Mar 17 22:13:39 flux systemd[1]: ffplayout-engine.service: Service RestartSec=1s expired, scheduling restart.
Mar 17 22:13:39 flux systemd[1]: ffplayout-engine.service: Scheduled restart job, restart counter is at 5.
Mar 17 22:13:39 flux systemd[1]: Stopped python and ffmpeg based playout.
Mar 17 22:13:39 flux systemd[1]: ffplayout-engine.service: Start request repeated too quickly.
Mar 17 22:13:39 flux systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Mar 17 22:13:39 flux systemd[1]: Failed to start python and ffmpeg based playout.
```

**Comment by linnikvv** [comment]
v2.0.0 works fine, but v3.0.0 does not start

**Comment by jb-alvarado** [comment]
Please put your logging output in a code block (start and end with ```), this makes it easer to read. And when you think this is a bug, use the Bug report template.

Have you try to fix this issue here?:

```
PermissionError: [Errno 13] Permission denied: '/var/log/ffplayout/decoder.log'
```

The file or parent folder has a different permission, then the running process. When the ffplayout-engine for example runs under the user **www-data**, then the logging folder and its files must have the owner **www-data** to.
