### ISSUE TITLE
Error while opening encoder for output stream

### ISSUE THREAD

**Issue by creativebeast2021** [ffplayout/ffplayout-engine#92]
### What am I trying to do?
I am trying to setup `ffplayout` for my experiment on HLS live stream.

### What have I done till now?
- Installed `ffmpeg`(4.3.2) and `ffprobe`(4.3.2) via brew
- Cloned `ffplayout` repo and running using python command

### What is the issue I am facing?

Config file I use for `ffplayout`:

```
general:
    helptext: Sometimes it can happen, that a file is corrupt but still playable,
        this can produce an streaming error over all following files. The only way
        in this case is, to stop ffplayout and start it again here we only say it
        can stop, the starting process is in your hand. Best way is a systemd serivce
        on linux. 'stop_threshold' stop ffplayout, if it is async in time above this
        value.
    stop_on_error: True
    stop_threshold: 11

mail:
    helptext: Send error messages to email address, like missing playlist; unvalid
        json format; missing clip path. Leave recipient blank, if you don't need this.
        'mail_level' can be WARNING or ERROR.
    subject: "Playout Error"
    smpt_server: "mail.example.org"
    smpt_port: 587
    sender_addr: "ffplayout@example.org"
    sender_pass: "abc123"
    recipient:
    mail_level: "ERROR"

logging:
    helptext: Logging to file, if 'log_to_file' False log to console. 'backup_count'
        says how long log files will be saved in days. Path to /var/log/ only if you
        run this program as deamon. 'log_level' can be DEBUG, INFO, WARNING,
        ERROR. 'ffmpeg_level' can be INFO, WARNING, ERROR.
    log_to_file: True
    backup_count: 7
    log_path: "/var/log/ffplayout/"
    log_level: "DEBUG"
    ffmpeg_level: "ERROR"

processing:
    helptext: Default processing, for all clips that they get prepared in that way,
        so the output is unique. 'aspect' must be a float number. 'logo' is only used
        if the path exist. 'logo_scale' scale the logo to target size, leave it blank
        when no scaling is needed, format is 'number:number', for example '100:-1'
        for proportional scaling. With 'logo_opacity' logo can become transparent.
        With 'logo_filter' 'overlay=W-w-12:12' you can modify the logo position.
        With 'use_loudnorm' you can activate single pass EBU R128 loudness normalization.
        'loud_*' can adjust the loudnorm filter. 'output_count' sets the outputs for
        the filtering, > 1 gives the option to use the same filters for multiple outputs.
        This outputs can be taken in 'ffmpeg_param', names will be vout2, vout3;
        aout2, aout2 etc.'use_realtime' is realtime filter, it works not in all scenarios,
        but for example is necessary for hls output.
    width: 1024
    height: 576
    aspect: 1.778
    fps: 25
    add_logo: False
    logo: "docs/logo.png"
    logo_scale:
    logo_opacity: 0.7
    logo_filter: "overlay=W-w-12:12"
    add_loudnorm: False
    loud_I: -18
    loud_TP: -1.5
    loud_LRA: 11
    output_count: 1
    use_realtime: false

playlist:
    helptext: Set 'playlist_mode' to 'False' if you want to play clips from the 'storage'
        section. Put only the root path here, for example '/playlists' subfolders
        are readed by the script. Subfolders needs this structur '/playlists/2018/01'
        (/playlists/year/month). 'day_start' means at which time the playlist should
        start, leave day_start blank when playlist should always start at the begin.
        'length' represent the target length from playlist, when is blank real length
        will not consider.
    playlist_mode: False
    path: "/playlists"
    day_start: "5:59:25"
    length: "24:00:00"

storage:
    helptext: Play ordered or ramdomly files from path. 'filler_clip' is for fill
        the end to reach 24 hours, it will loop when is necessary. 'extensions' search
        only files with this extension. Set 'shuffle' to 'True' to pick files randomly.
    path: "videos"
    filler_clip: "/mediaStorage/filler/filler.mp4"
    extensions:
        - ".mp4"
    shuffle: False

text:
    helptext: Overlay text in combination with libzmq for remote text manipulation.
        On windows fontfile path need to be like this 'C\:/WINDOWS/fonts/DejaVuSans.ttf'.
        In a standard environment the filter drawtext node is Parsed_drawtext_2.
        'over_pre' if True text will be overlay in pre processing. Continue same text
        over multiple files is in that mode not possible. 'text_from_filename' activate the
        extraction from text of a filename. With 'style' you can define the drawtext
        parameters like position, color, etc. Post Text over API will override this.
        With 'regex' you can format file names, to get a title from it.
    add_text: False
    over_pre: False
    bind_address: "127.0.0.1:5555"
    fontfile: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    text_from_filename: False
    style: "x=(w-tw)/2:y=(h-line_h)*0.9:fontsize=24:fontcolor=#ffffff:box=1:boxcolor=#000000:boxborderw=4"
    regex: "^(.*)_"

out:
    helptext: The final playout compression. Set the settings to your needs.
        'mode' has the standard options 'desktop', 'hls', 'stream'. Self made outputs
        can be define, by adding script in output folder with an 'output' function inside.
        'stream_output' is for streaming output, two ffmpeg instances are fired up, for
        pre- and post-processing. 'hls_output' is for direct output to hls playlist,
        without pre- and post-processing, mode must be 'hls'.
    mode: 'stream'
    service_name: "Live Stream"
    service_provider: "example.org"
    ffmpeg_param: >-
        -c:v libx264
        -crf 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 1300k
        -bufsize 2600k
        -preset medium
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
    stream_output: >-
        -flags +global_header
        -f flv rtmp://localhost/live/stream
    hls_output: >-
        -flags +cgop
        -f hls
        -hls_time 6
        -hls_list_size 600
        -hls_flags append_list+delete_segments+omit_endlist+program_date_time
        -hls_segment_filename stream-%09d.ts stream.m3u8

```

Command I use to run `ffplayout`:

`python ffplayout.py -l none -m hls`

Output of command:

```
[2021-03-23 14:54:17,306][WARNING]  ffmpeg contains no libfdk-aac! No high quality aac...
[2021-03-23 14:54:17,459][INFO]     Start folder mode
[2021-03-23 14:54:17,589][WARNING]  Clip "videos/vid1.mp4" has no audio!
[2021-03-23 14:54:17,589][INFO]     Play: videos/vid1.mp4
[2021-03-23 14:54:17,590][DEBUG]    Encoder CMD: "ffmpeg -v error -hide_banner -nostats -i videos/vid1.mp4 -filter_complex [0:v]fps=25,scale=1024:576[v];[v]null[vout1] -filter_complex aevalsrc=0:channel_layout=2:duration=559.30875:sample_rate=48000[aout1] -map [vout1] -map [aout1] -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2021 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist+program_date_time -hls_segment_filename stream-%09d.ts stream.m3u8"
[2021-03-23 14:54:17,716][ERROR]    [encoder] [aac @ 0x7fb015870a00] Unsupported channel layout "1 channels (FR)"
[2021-03-23 14:54:17,716][ERROR]    [encoder] Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
[2021-03-23 14:54:17,726][DEBUG]    cleanup *.ts files from: "stream.m3u8"
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/username/Downloads/ffplayout-engine/ffplayout/output/hls.py", line 27, in clean_ts
    with open(playlist, 'r') as m3u8:
FileNotFoundError: [Errno 2] No such file or directory: 'stream.m3u8'
[2021-03-23 14:54:17,802][WARNING]  Clip "videos/vid1.mp4" has no audio!
```

FFProbe on the `vid1.mp4` file:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid1.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2021-03-23T06:19:24.000000Z
  Duration: 00:09:19.31, start: 0.000000, bitrate: 2185 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 18 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2021-03-23T06:19:24.000000Z
      handler_name    : ISO Media file produced by Google Inc.
```

What am I doing wrong here?

**Comment by jb-alvarado** [comment]
I set the channel layout wrong, from empty audio files. Can you try the repo again?

**Comment by creativebeast2021** [comment]
@jb-alvarado thanks for the ultra fast response. i pulled in the latest but now getting a different error:

```
[2021-03-23 19:42:46,092][WARNING]  ffmpeg contains no libfdk-aac! No high quality aac...
[2021-03-23 19:42:46,334][INFO]     Start folder mode
[2021-03-23 19:42:46,420][WARNING]  Clip "videos/vid1.mp4" has no audio!
[2021-03-23 19:42:46,420][INFO]     Play: videos/vid1.mp4
[2021-03-23 19:42:46,420][DEBUG]    Encoder CMD: "ffmpeg -v error -hide_banner -nostats -i videos/vid1.mp4 -filter_complex [0:v]fps=25,scale=1024:576[v];[v]null[vout1] -filter_complex anullsrc:channel_layout=stereo:duration=559.30875:sample_rate=48000[aout1] -map [vout1] -map [aout1] -metadata service_name=Live Stream -metadata service_provider=example.org -metadata year=2021 -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1 -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a aac -ar 44100 -b:a 128k -flags +cgop -f hls -hls_time 6 -hls_list_size 600 -hls_flags append_list+delete_segments+omit_endlist+program_date_time -hls_segment_filename stream-%09d.ts stream.m3u8"
[2021-03-23 19:42:46,497][ERROR]    [encoder] [AVFilterGraph @ 0x7fe33b829a40] No such filter: 'anullsrc:channel_layout'
[2021-03-23 19:42:46,497][ERROR]    [encoder] Error initializing complex filters.
[2021-03-23 19:42:46,497][ERROR]    [encoder] Invalid argument
```

**Comment by jb-alvarado** [comment]
Hm that is strange... Maybe that works different in different ffmpeg versions. Can you do me a favour and change the line 163 in **filters/default.py** from:

```python
anullsrc:channel_layout=stereo
```
to:
```python
f'aevalsrc=0:channel_layout=stereo
```
And see if that works?

**Comment by creativebeast2021** [comment]
Yes thank you. It is working now.

**Comment by creativebeast2021** [comment]
@jb-alvarado one quick question: is there any way to run custom yml files? like i have test1.yml and test2.yml lets assume I want to run them. Is there a way from CLI to do that instead of the picking from default yml file??

**Comment by jb-alvarado** [comment]
Yes of course! just pass `-c /path/to/config.yml`

**Comment by creativebeast2021** [comment]
Thanks @jb-alvarado missed this in the README somehow!

**Comment by creativebeast2021** [comment]
Also a different question @jb-alvarado:

I am doing watch folder mode. I want to pause the looping thing until a new video is added. In simple words, if there is video 1.mp4, 2.mp4 and 3.mp4. I want to wait for the 4.mp4 to be added but what actually happens is that its keeps looping from 1.mp4 again after finishing parsing 3.mp4
